### ISSUE TITLE
acp.php / german

### ISSUE THREAD

**Issue by jan-2017** [marttiphpbb/phpbb-ext-topictemplate#3]
<?php

/**
* phpBB Extension - marttiphpbb Topic Template
* @copyright (c) 2015 - 2018 marttiphpbb <info@martti.be>
* @license GNU General Public License, version 2 (GPL-2.0)
*/

if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = [];
}

$lang = array_merge($lang, [

	'ACP_MARTTIPHPBB_TOPICTEMPLATE'			=> 'Beitragsvorlage',
	'ACP_MARTTIPHPBB_TOPICTEMPLATE_EXPLAIN'	=> 'Wird im Forum auf den Button "Neues Thema" geklickt , läd eine "Beitragsvorlage" im Texteditor, die du hier individuell erstellen kannst.

Möchtest du keine Beitragsvorlage, dann lass das Feld frei. Diese Funktion kommt aus der Extension "Topic Template".',
]);

**Comment by marttiphpbb** [comment]
Maybe you could fork and send a pull request?

**Comment by jan-2017** [comment]
How could i do that?

marttiphpbb <notifications@github.com> schrieb am Fr., 20. Apr. 2018, 21:27:

**Comment by marttiphpbb** [comment]
If you have no experience with Git, then the most easy is here online on Github I guess. In this repo, push the button "Fork" in the upper right corner. This gives you your own private version of this code where you can do what you want. In your version you can add the file (upload or online edit).  Then "commit" and come back to this repo to hit "pull reqeust" (See also the Github guides or other tutorials.)
